// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class Address
    {
        public int Idaddress { get; set; }
        public int? SchoolIdschool { get; set; }
        public string Street { get; set; }
        public int PostalCode { get; set; }
        public string Country { get; set; }
        public int Number { get; set; }

        public virtual School SchoolIdschoolNavigation { get; set; }
    }
}