// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class AttendanceKey
    {
        public string IdattendanceKey { get; set; }
        public DateTime ValidUntil { get; set; }
        public int LessonUserIduser { get; set; }
        public int LessonClassIdclass { get; set; }

        public virtual Lesson Lesson { get; set; }
    }
}