// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class Class
    {
        public Class()
        {
            Lessons = new HashSet<Lesson>();
        }

        public int Idclass { get; set; }
        public int CourseIdcourse { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public int NumberOfClass { get; set; }

        public virtual Course CourseIdcourseNavigation { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}