// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class Lesson
    {
        public Lesson()
        {
            AttendanceKeys = new HashSet<AttendanceKey>();
        }

        public int UserIduser { get; set; }
        public int ClassIdclass { get; set; }
        public bool Present { get; set; }

        public virtual Class ClassIdclassNavigation { get; set; }
        public virtual User UserIduserNavigation { get; set; }
        public virtual ICollection<AttendanceKey> AttendanceKeys { get; set; }
    }
}