// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class Role
    {
        public Role()
        {
            UserRoles = new HashSet<UserRole>();
        }

        public int Idrole { get; set; }
        public string Role1 { get; set; }

        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}