// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Skoleprotokol.Dtos;
using System;
using System.Collections.Generic;

#nullable disable

namespace Skoleprotokol.Models
{
    public partial class User
    {
        
        public User()
        {
            Lessons = new HashSet<Lesson>();
            UserRoles = new HashSet<UserRole>();
        }

        public int Iduser { get; set; }
        public int SchoolIdschool { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool? Active { get; set; }

        public virtual School SchoolIdschoolNavigation { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}